### ISSUE TITLE
Lags in 4.1.0 Version

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.12#265]
I experienced strong lags when being near to bibliocraft blocks. It was not the case for 4.0.3.100 . When taking a look at the performance profiling Shift+F3 in minecraft the cathegory gameRenderer.level.terrain_setup.rebuildNear went up very high.

No growthcraft blocks were placed in the world, which is kind of strange ...

**Comment by darthvader45** [comment]
Had a similar problem with GC beehives during worldgen, which caused the game to hang, and ultimately forced me to close it.  I was using the Quark Realistic worldtype.  I don't see why it would have any problems, as it's literally a wrapper for a vanilla preset.

**Comment by darthvader45** [comment]
Okay, try the 4.1.1 release on the releases tab of this repo.  Should clear that problem up, at least with the beehives.

**Comment by Alatyami** [comment]
Fixed in 4.1.1

**Comment by Avatair** [comment]
Is still occuring on rendering at terrain_setup.rebuildNear

![grafik](https://user-images.githubusercontent.com/21110130/70848675-6142dc00-1e75-11ea-8c55-c27e3cafa7ad.png)

**Comment by Avatair** [comment]
Update: I identified, that this issue was introduced between 4.0.4.500 and 4.0.5.100.

**Comment by Avatair** [comment]
Finally found the buggy merge commit. It seems that the Waila integration causes it.
The commit 83f7db5bde787ca32e02497e8bbf6b62c040e502 on 2019-05-24 18:07:13 seems to have introduced rendering issues.

**Comment by Alatyami** [comment]
That's a good question. I'll check my notes.

**Comment by Alatyami** [comment]
Figured it out. So, the waila integration example had needed the TileEntity to sync more between the client/server. replaced the three lines to a simple markDirtyAndUpdate and now it should be scheduled instead of forced. The FermentBarrel.update() only updates the device class and not the TileEntity for the given barrel.

**Comment by darthvader45** [comment]
Good to know.

**Comment by Avatair** [comment]
Still occurs. Only removing these lines helped.

I wouldn't expect, that using a scheduled variant instead would help. On the client side it will trigger a mesh rebuilding anyways. We need then something, which synchronizes the TileEntities but doesn't trigger a mesh update. Maybe a custom network package could help here.

**Comment by Avatair** [comment]
Got finally everything working. Waila update without lags. Can somebody do a test of branch bugfix/265-render-lag-fix-atempt-2 using singleplayer scenario and also a server/client scenario?

Also, we really need to revise the whole chain of block updates and server/client communication stuff some day. It is a hacky mess here.

**Comment by Avatair** [comment]
Fixing GrowthcraftTileBase.onDataPacket() seems to break the cheese block :(

**Comment by darthvader45** [comment]
That sucks, I like my cheese blocks.

**Comment by Avatair** [comment]
Don't worry. Cheese is working again. It got broken temporarily, because it relies on one code line I changed.

**Comment by xJon** [comment]
So is it recommended to use `4.1.1` or `4.1.1.300` from CurseForge?

**Comment by Alatyami** [comment]
Recommend waiting for 4.1.1.400 come out later today. We're going to release either 4.2.0 or 4.1.2 before the 25th. Of note the x.x.x are the stable releases and the x.x.x.x are the snapshot releases.

**Comment by xJon** [comment]
I see. I planned to release a modpack update today, so if you say so I will wait for `4.1.1.400` instead of updating only to `4.1.1`.

**Comment by Alatyami** [comment]
That did the trick. Major improvement to performance.

**Comment by Alatyami** [comment]
@xJon https://github.com/GrowthcraftCE/Growthcraft-1.12/releases/tag/4.1.1.400

**Comment by xJon** [comment]
Thank you!
